id: A2BF10739
base_file: f0E70.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:44:16.775692
  last_modified_at: 2022-05-31 06:44:16.775701
