id: A2BF10739
base_file: fB546.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:44:16.782630
  last_modified_at: 2022-05-31 06:44:16.782662
