id: A2BF10739
base_file: fC9C4.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:44:16.786472
  last_modified_at: 2022-05-31 06:44:16.786478
